### ISSUE TITLE
Choose version is getting to specific 

### ISSUE THREAD

**Issue by Hogfeldt** [Hogfeldt/bioconda_recipe_gen#154]
In the current test with a sample of 30 python packages, the package `stream` fails with the following message:

```
conda.exceptions.UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

  - anndata[version='>=0.7.1'] -> python[version='>=3.6,<3.7.0a0']
  - numpy[version='>=1.18.1'] -> python[version='>=3.6,<3.7.0a0']
  - pandas[version='>=1.0.1'] -> python[version='>=3.7,<3.8.0a0']

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you've asked for.
Your current python version is (python[version='>=3.8,<3.9.0a0']).

The following specifications were found to be incompatible with each other:

  - python[version='>=3.8,<3.9.0a0']
```

The generated `meta.yaml` look like this:
```
package:
  name: stream
  version: 0.4.1
source:
  url: https://github.com/pinellolab/STREAM/archive/v0.4.1.zip
  sha256: a09833e849dd4b4b805acc1cbc39af5be837595ce84a676d984e5f51a0b5b0fa
build:
  number: 5
requirements:
  host:
  - python >=3
  run:
  - python >=3
  - numpy>=1.18.1
  - pandas>=1.0.1
  - pandas
  - anndata>=0.7.1
test:
  imports:
  - stream
```

The problem is that we are getting to specific on which version to choose. This results in an environment where we cannot find a version of python which satisfies all packages and therefore ends up in an environment which cannot be solved. 
Instead of choosing a specific version I think it would be better to just add the packages without a version and let conda solve the problem of finding a compatible set of versions.
