### ISSUE TITLE
When building Kallisto, hdf5 occurs more than one time in host

### ISSUE THREAD

**Issue by Hogfeldt** [Hogfeldt/bioconda_recipe_gen#22]
I have just tried to run our pipeline. The output is the following meta.yaml:
```
package:
  name: kallisto2
  version: 0.45.0
source:
  url: https://github.com/pachterlab/kallisto/archive/v0.45.0.tar.gz
  sha256: b32c74cdc0349c2fe0847b3464a3698da89212a507332a06291b6fc27b4e2305
requirements:
  build:
  - cmake
  - make
  - {{ compiler('cxx') }}
  - zlib
  - autoconf
  - hdf5
  host:
  - hdf5
  - hdf5
  - hdf5
  - zlib
  - autoconf
  - hdf5
  run:
  - hdf5
test:
  command:
  - kallisto version
```
hdf5 should only occur once in the host. This issue is probably related to issue #21
