### ISSUE TITLE
Test if kallisto2 depends on hdf5 when installing the package

### ISSUE THREAD

**Issue by Hogfeldt** [Hogfeldt/bioconda_recipe_gen#31]
When conda-build runs the kallisto tests, the test succeeds even though hdf5 isn't added as a dependency at run-time. 

When giving the following meta.yaml:
```
package:
  name: kallisto2
  version: 0.45.0
source:
  url: https://github.com/pachterlab/kallisto/archive/v0.45.0.tar.gz
  sha256: b32c74cdc0349c2fe0847b3464a3698da89212a507332a06291b6fc27b4e2305
requirements:
  build:
  - cmake
  - make
  - {{ compiler('cxx') }}
  - autoconf
  - automake
  host:
  - hdf5
test:
  commands:
  - kallisto version
  files:
  - t.fq
  - t.fa
```

Conda-build creates the following test environment:
```
    hdf5:           1.10.4-nompi_h3c11f04_1106 conda-forge
    kallisto2:      0.45.0-h6bb024c_0          local      
    libgcc-ng:      8.2.0-hdf63c60_1                      
    libgfortran-ng: 7.3.0-hdf63c60_0                      
    libstdcxx-ng:   8.2.0-hdf63c60_1                      
    zlib:           1.2.11-h14c3975_1004       conda-forge
```

It seems like when hdf5 is added as a host dependency it also includes hdf5 at run-time. We should extract the package which conda-build creates and try to install it in an empty environment to test if it also installs hdf5 in the environment. 

If this is the case, we should consider not to using host and only use build and run. It is also possible that it is an issue with conda-build and we should consider reporting it.
