### ISSUE TITLE
Make clever-toolkit pass sanity check

### ISSUE THREAD

**Issue by Hogfeldt** [Hogfeldt/bioconda_recipe_gen#61]

**Comment by Hogfeldt** [comment]
clever-toolkit passes the sanity check with the following dependencies:
```
requirements:
  build:
  - make
  - cmake
  - {{ compiler('cxx') }}
  host:
  - boost
  run:
  - boost
  - zlib
```
The dependencies defined in the original meta.yaml is:
```
requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - python
    - boost
    - cmake
    - zlib
  run:
    - python
    - boost
    - zlib
    - bedtools >=2.26
    - bwa
    - samtools >=1
    - bcftools >=1
    - matplotlib 2
    - make
```
There is a lot of packages which we don't detect. It's is probably because of tests with low coverage. We should have a discussion about rather this is a successful build or not.
